"""extend_phone_varchar

Revision ID: 910f2ff71fa0
Revises: de6851a4292d
Create Date: 2026-05-05 13:21:00.238540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910f2ff71fa0'
down_revision: Union[str, Sequence[str], None] = 'de6851a4292d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
