"""add_identity_fields

Revision ID: c7837e7b8afe
Revises: 910f2ff71fa0
Create Date: 2026-05-15 08:12:07.802755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7837e7b8afe'
down_revision: Union[str, Sequence[str], None] = '910f2ff71fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('father_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('customers', sa.Column('birth_place', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'birth_place')
    op.drop_column('customers', 'father_name')
    # ### end Alembic commands ###
