"""initial_schema

Revision ID: de6851a4292d
Revises: 
Create Date: 2026-05-05 13:14:40.640378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6851a4292d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('national_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('checking', 'savings', 'time_deposit', 'credit_card', name='account_type'), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('iban', sa.VARCHAR(length=34), nullable=True),
    sa.Column('status', sa.Enum('active', 'frozen', 'closed', name='account_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('chat', 'voice', name='conversation_mode'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('loans',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('personal', 'mortgage', 'vehicle', name='loan_type'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'active', 'closed', name='loan_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('support_tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='ticket_priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('credit_cards',
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('card_number_masked', sa.VARCHAR(length=19), nullable=False),
    sa.Column('credit_limit', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('available_limit', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('billing_date', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', 'expired', name='credit_card_status'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('credit_card_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('tool_used', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'debit', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('messages')
    op.drop_table('credit_cards')
    op.drop_table('support_tickets')
    op.drop_table('loans')
    op.drop_table('conversations')
    op.drop_table('accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###
